In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('/content/FakeNews.csv')

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [5]:
df=df.dropna()

In [6]:
df=df.reset_index()

In [7]:
df.isnull().sum()

index     0
id        0
title     0
author    0
text      0
label     0
dtype: int64

In [8]:
##Dependent and Independent Features
X=df.drop('label',axis=1)

In [9]:
y=df['label']

In [10]:
X.shape,y.shape

((18285, 5), (18285,))

In [11]:
message=X.copy()

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Dense,LSTM
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [13]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [14]:
ps=PorterStemmer()

In [15]:
corpus=[]
for i in range(0,len(message)):
  review=re.sub('[^a-zA-Z]',' ',message['title'][i])
  review=review.lower()
  review=review.split()

  review=[ps.stem(word) for word in review if word not in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [16]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [17]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [18]:
### One hot Encdoing
voc_size=5000

In [19]:
onehot_repre=[one_hot(word,voc_size) for word in corpus]

In [20]:
onehot_repre

[[1441, 4309, 3062, 4918, 651, 2600, 4505, 1838, 563, 276],
 [4143, 3459, 3668, 3207, 43, 1364, 4208],
 [1683, 40, 4432, 3314],
 [982, 3488, 1813, 3189, 4321, 2551],
 [2332, 43, 1738, 143, 2501, 4397, 43, 3062, 4280, 918],
 [2576,
  1779,
  2056,
  3130,
  3013,
  2890,
  1214,
  532,
  2515,
  4017,
  684,
  874,
  2434,
  3813,
  4208],
 [550, 3740, 2263, 3116, 1329, 2876, 801, 4861, 964, 2816, 3460],
 [1764, 77, 20, 1675, 1509, 3607, 2890, 2373, 964, 2816, 3460],
 [1203, 3784, 1760, 3800, 3632, 709, 3385, 1221, 2890, 3979],
 [1015, 1050, 1597, 2152, 2697, 3070, 592, 3513],
 [4210, 4239, 1344, 2625, 2022, 4522, 4806, 3848, 3345, 2828, 1379],
 [3189, 2512, 651, 709, 2890, 1509],
 [2588, 2734, 3607, 1668, 2362, 1732, 3663, 927, 3427],
 [4468, 289, 499, 2750, 705, 4681, 4508, 964, 2816, 3460],
 [4372, 939, 4421, 1778, 2008, 964, 2816, 3460],
 [2239, 3228, 23, 4644, 4379, 1605, 4836, 1590, 2231, 1370],
 [196, 71, 3459],
 [1346, 3851, 4298, 3490, 2890, 4734, 1153, 4208],
 [2357, 4520, 366

In [ ]:
### Embedding

In [21]:
embedding_docs=pad_sequences(onehot_repre,padding='pre',maxlen=20)

In [22]:
embedding_docs

array([[   0,    0,    0, ..., 1838,  563,  276],
       [   0,    0,    0, ...,   43, 1364, 4208],
       [   0,    0,    0, ...,   40, 4432, 3314],
       ...,
       [   0,    0,    0, ...,  964, 2816, 3460],
       [   0,    0,    0, ..., 2559, 1964, 4349],
       [   0,    0,    0, ..., 3619,  515, 3169]], dtype=int32)

In [23]:
embedding_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1441,
       4309, 3062, 4918,  651, 2600, 4505, 1838,  563,  276], dtype=int32)

In [ ]:
### Model Building

In [26]:
model=Sequential()
voc_size=5000
embedding_vector_features=40
model.add(Embedding(voc_size,embedding_vector_features))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])




In [28]:
X_final=np.array(embedding_docs)
y_final=np.array(y)

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train,X_test,y_train,y_test=train_test_split(X_final,y_final,train_size=0.33, random_state=42)

In [31]:
model.fit(X_train,y_train,validation_data=(X_final,y_final),epochs=10,batch_size=64)

Epoch 1/10
95/95 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - accuracy: 0.7221 - loss: 0.5206 - val_accuracy: 0.9027 - val_loss: 0.2130
Epoch 2/10
95/95 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.9280 - loss: 0.1793 - val_accuracy: 0.9343 - val_loss: 0.1623
Epoch 3/10
95/95 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.9605 - loss: 0.1077 - val_accuracy: 0.9365 - val_loss: 0.1595
Epoch 4/10
95/95 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.9840 - loss: 0.0590 - val_accuracy: 0.9350 - val_loss: 0.1707
Epoch 5/10
95/95 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.9889 - loss: 0.0404 - val_accuracy: 0.9384 - val_loss: 0.1840
Epoch 6/10
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.9945 - loss: 0.0210 - val_accuracy: 0.9385 - val_loss: 0.2501
Epoch 7/10
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.9987 - loss: 0.0084 - val_accuracy: 0.9345 - val_loss: 0.2662
Epoch 8/10
95/95 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.9981 - loss: 0.0068 - val_accuracy: 0.9351 - v

In [32]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ (None, 20, 40)              │         200,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ (None, 100)                 │          56,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │             101 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 769,505 (2.94 MB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 513,004 (1.96 MB)

In [33]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [41]:
y_predict=model.predict(X_test)

383/383 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


In [42]:
y_predict=np.where(y_predict>0.6,1,0)

In [43]:
co_matrix=confusion_matrix(y_predict,y_test)
accuracy=accuracy_score(y_predict,y_test)
classification=classification_report(y_predict,y_test)

In [44]:
print(co_matrix)
print(accuracy)
print(classification)

[[6342  531]
 [ 618 4760]]
0.906211737817321
              precision    recall  f1-score   support

           0       0.91      0.92      0.92      6873
           1       0.90      0.89      0.89      5378

    accuracy                           0.91     12251
   macro avg       0.91      0.90      0.90     12251
weighted avg       0.91      0.91      0.91     12251

