In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import make_classification

In [3]:
X,y=make_classification(n_classes=2,n_features=3,n_samples=5000,n_redundant=1,random_state=42)

In [4]:
X,y

(array([[ 0.67773652,  0.78399016,  0.39945361],
        [ 0.8621084 ,  0.97929418,  0.8641888 ],
        [-1.53044679, -1.72528357, -1.79556234],
        ...,
        [-0.89629695, -1.12059981,  1.13157832],
        [-2.78044942, -3.17491203, -2.4599179 ],
        [-1.12021107, -1.2864727 , -0.8457151 ]]),
 array([0, 1, 0, ..., 0, 0, 0]))

### Train Test Split Data

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

### Import KNN

In [7]:
from sklearn.neighbors import KNeighborsClassifier

In [8]:
KNN=KNeighborsClassifier(n_neighbors=5,algorithm='auto')

In [9]:
KNN.fit(X_train,y_train)

KNeighborsClassifier()

In [10]:
y_predict=KNN.predict(X_test)

### Performance Metrics Calculations

In [11]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [12]:
score=accuracy_score(y_predict,y_test)
creport=classification_report(y_predict,y_test)
cmatrix=confusion_matrix(y_predict,y_test)

In [13]:
print(score)
print(creport)
print(cmatrix)

0.9121212121212121
              precision    recall  f1-score   support

           0       0.91      0.91      0.91       819
           1       0.91      0.91      0.91       831

    accuracy                           0.91      1650
   macro avg       0.91      0.91      0.91      1650
weighted avg       0.91      0.91      0.91      1650

[[745  74]
 [ 71 760]]


### Grid Search CV

In [14]:
from sklearn.model_selection import GridSearchCV

In [19]:
parameter={ 'n_neighbors': [1,2,3,4,5,6,7,8],
            'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
           'weights': ['uniform', 'distance']
          }

In [20]:
Kn=KNeighborsClassifier()

In [21]:
gsearch=GridSearchCV(Kn,param_grid=parameter,cv=5)

In [22]:
gsearch.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8],
                         'weights': ['uniform', 'distance']})

### Best parameters

In [23]:
gsearch.best_params_

{'algorithm': 'auto', 'n_neighbors': 7, 'weights': 'uniform'}

In [24]:
y_predicts=gsearch.predict(X_test)

In [25]:
score=accuracy_score(y_predict,y_test)
creport=classification_report(y_predict,y_test)
cmatrix=confusion_matrix(y_predict,y_test)

In [26]:
print(score)
print(creport)
print(cmatrix)

0.9121212121212121
              precision    recall  f1-score   support

           0       0.91      0.91      0.91       819
           1       0.91      0.91      0.91       831

    accuracy                           0.91      1650
   macro avg       0.91      0.91      0.91      1650
weighted avg       0.91      0.91      0.91      1650

[[745  74]
 [ 71 760]]
