In [1]:
import numpy as np

In [2]:
np.array([1,2,3,45,5])

array([ 1,  2,  3, 45,  5])

In [3]:
type(np.array([1,2,3,45,5]))

numpy.ndarray

In [4]:
np.asarray([1,2,3,4,5,6,6,9])

array([1, 2, 3, 4, 5, 6, 6, 9])

In [5]:
type(np.asarray([1,2,3,4,5,6,6,9]))

numpy.ndarray

In [8]:
np.matrix([[2,3,34,4,3,3,3,3,3],[2,3,34,4,3,3,3,3,3]])

matrix([[ 2,  3, 34,  4,  3,  3,  3,  3,  3],
        [ 2,  3, 34,  4,  3,  3,  3,  3,  3]])

In [9]:
test=np.matrix([[2,3,34,4,3,3,3,3,3],[2,3,34,4,3,3,3,3,3]])

In [10]:
type(test)

numpy.matrix

In [11]:
a=np.array([3,5,7,9,11,13,15,17,19])

In [12]:
c=a


In [13]:
c[1]=100

In [14]:
a

array([  3, 100,   7,   9,  11,  13,  15,  17,  19])

In [15]:
d=np.copy(a)

In [17]:
d[0]=100

In [18]:
a

array([  3, 100,   7,   9,  11,  13,  15,  17,  19])

In [19]:
d

array([100, 100,   7,   9,  11,  13,  15,  17,  19])

In [46]:
np.fromfunction(lambda x,y: x==y,(5,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False]])

In [48]:
np.fromfunction(lambda x,y: x**y , (5,3))

array([[ 1.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  2.,  4.],
       [ 1.,  3.,  9.],
       [ 1.,  4., 16.]])

In [23]:
tem=(i*i for i in range(10))

In [25]:
np.fromiter(tem,int)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [26]:
temp=(i+2 for i in range(5))

In [27]:
np.fromiter(temp,int)

array([2, 3, 4, 5, 6])

In [28]:
np.fromstring('1111 2222 333',sep=' ')

array([1111., 2222.,  333.])

In [34]:
ans=np.fromstring('222 222',sep=' ')

In [35]:
ans.ndim

1

In [38]:
array=np.array([[[2,3,3],[3,3,3]]])

In [39]:
array.ndim

3

In [41]:
ans.size

2

In [42]:
array.size

6

In [43]:
array.shape

(1, 2, 3)

In [44]:
ans.shape

(2,)

In [49]:
list(range(1,3))

[1, 2]

In [52]:
list(range(1,100,5))

[1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96]

In [53]:
list(range(1,10,0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [56]:
list(np.arange(1,3,0.5))

[1.0, 1.5, 2.0, 2.5]

In [57]:
np.arange(3,10,2.2)

array([3. , 5.2, 7.4, 9.6])

In [59]:
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [60]:
np.linspace(7,100,25)

array([  7.   ,  10.875,  14.75 ,  18.625,  22.5  ,  26.375,  30.25 ,
        34.125,  38.   ,  41.875,  45.75 ,  49.625,  53.5  ,  57.375,
        61.25 ,  65.125,  69.   ,  72.875,  76.75 ,  80.625,  84.5  ,
        88.375,  92.25 ,  96.125, 100.   ])

In [62]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
np.zeros((3,3,3,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [64]:
np.empty((3,3))

array([[4.64790472e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [67]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [76]:
np.logspace(2,100,100, base=2)

array([4.00000000e+00, 7.94418373e+00, 1.57775138e+01, 3.13348671e+01,
       6.22324854e+01, 1.23596575e+02, 2.45468474e+02, 4.87511665e+02,
       9.68220560e+02, 1.92293051e+03, 3.81902831e+03, 7.58476564e+03,
       1.50636930e+04, 2.99171861e+04, 5.94169059e+04, 1.18004704e+05,
       2.34362763e+05, 4.65455212e+05, 9.24415432e+05, 1.83593151e+06,
       3.64624431e+06, 7.24160868e+06, 1.43821675e+07, 2.85636452e+07,
       5.67287114e+07, 1.12665827e+08, 2.23759507e+08, 4.44396658e+08,
       8.82592176e+08, 1.75286860e+09, 3.48127756e+09, 6.91397714e+09,
       1.37314762e+10, 2.72713424e+10, 5.41621387e+10, 1.07568495e+11,
       2.13635973e+11, 4.24290855e+11, 8.42661126e+11, 1.67356370e+12,
       3.32377439e+12, 6.60116860e+12, 1.31102241e+13, 2.60375072e+13,
       5.17116852e+13, 1.02701782e+14, 2.03970457e+14, 4.05094696e+14,
       8.04536674e+14, 1.59784679e+15, 3.17339712e+15, 6.30251244e+15,
       1.25170792e+16, 2.48594943e+16, 4.93720975e+16, 9.80552534e+16,
      

In [78]:
np.random.randn(1,10)

array([[-0.38363301, -0.02000628,  0.43377888, -1.13462817,  0.71042612,
        -0.33894983, -2.1513035 , -0.64814302,  0.9696867 ,  0.79735541]])

In [79]:
np.random.rand(1,10)

array([[0.26288487, 0.24902498, 0.01399817, 0.20302734, 0.65160691,
        0.83124378, 0.92922988, 0.55753976, 0.11225822, 0.46810851]])

In [80]:
np.random.rand(2,100)

array([[5.44592039e-01, 2.23691260e-01, 6.71943353e-01, 2.00469068e-01,
        9.63515018e-01, 4.84614198e-01, 5.00176524e-01, 1.71405302e-01,
        9.58561161e-02, 6.67553388e-01, 1.36562421e-01, 8.83684544e-01,
        1.49702591e-01, 3.81795745e-02, 7.40057583e-02, 2.54909879e-01,
        1.48326092e-01, 3.74312764e-01, 3.00289159e-01, 7.15996137e-01,
        4.62761085e-01, 2.51806800e-01, 9.32005870e-01, 3.71189170e-01,
        2.13541009e-01, 1.61537395e-01, 3.87520701e-01, 7.84379342e-03,
        4.31599145e-01, 9.31434622e-01, 1.03640907e-01, 6.42513141e-01,
        9.11044432e-01, 3.08848196e-01, 6.62091077e-03, 8.43349557e-01,
        4.89553840e-02, 4.12257110e-01, 8.20420979e-01, 8.38154016e-01,
        6.26190928e-01, 1.94355523e-01, 5.13751000e-02, 5.70129314e-01,
        4.95600816e-01, 4.46032639e-01, 3.79374691e-01, 2.02363005e-01,
        4.37864204e-01, 8.37223695e-01, 8.72849093e-01, 7.61678269e-01,
        3.20308955e-01, 2.78644368e-01, 2.75796546e-01, 9.372465

In [81]:
arr=np.random.rand(3,4)

In [82]:
arr

array([[0.66994897, 0.11837959, 0.02607209, 0.37643808],
       [0.22215212, 0.46323653, 0.56543111, 0.82897557],
       [0.83436276, 0.35384585, 0.75261618, 0.46475353]])

In [83]:
arr.reshape(6,2)

array([[0.66994897, 0.11837959],
       [0.02607209, 0.37643808],
       [0.22215212, 0.46323653],
       [0.56543111, 0.82897557],
       [0.83436276, 0.35384585],
       [0.75261618, 0.46475353]])

In [85]:
arr.reshape(12,1)

array([[0.66994897],
       [0.11837959],
       [0.02607209],
       [0.37643808],
       [0.22215212],
       [0.46323653],
       [0.56543111],
       [0.82897557],
       [0.83436276],
       [0.35384585],
       [0.75261618],
       [0.46475353]])

In [86]:
np.sqrt(arr)

array([[0.81850411, 0.34406335, 0.16146853, 0.6135455 ],
       [0.47133016, 0.68061482, 0.75195154, 0.91048096],
       [0.91343459, 0.59484943, 0.86753454, 0.68172834]])

In [87]:
np.exp(10)

22026.465794806718

In [88]:
np.log10(arr)

array([[-0.17395827, -0.92672317, -1.58382423, -0.42430646],
       [-0.65334955, -0.3341972 , -0.2476203 , -0.08145827],
       [-0.07864509, -0.4511859 , -0.12342645, -0.3327773 ]])