In [2]:
import numpy as np

In [10]:
arr=np.random.randint(1,10,(2,6))

In [11]:
arr

array([[3, 2, 6, 5, 1, 9],
       [7, 6, 6, 5, 8, 9]])

In [12]:
arr.reshape(3,4)

array([[3, 2, 6, 5],
       [1, 9, 7, 6],
       [6, 5, 8, 9]])

In [14]:
arr.flatten()

array([3, 2, 6, 5, 1, 9, 7, 6, 6, 5, 8, 9])

In [15]:
arr.T

array([[3, 7],
       [2, 6],
       [6, 6],
       [5, 5],
       [1, 8],
       [9, 9]])

In [20]:
np.expand_dims(arr,axis=0)

array([[[3, 2, 6, 5, 1, 9],
        [7, 6, 6, 5, 8, 9]]])

In [22]:
np.expand_dims(arr,axis=1)

array([[[3, 2, 6, 5, 1, 9]],

       [[7, 6, 6, 5, 8, 9]]])

In [23]:
arr.squeeze()

array([[3, 2, 6, 5, 1, 9],
       [7, 6, 6, 5, 8, 9]])

In [24]:
arr2=np.array([[1],[2],[3]])

In [25]:
arr2.squeeze()

array([1, 2, 3])

In [26]:
np.repeat(arr2,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [28]:
np.roll(arr2,2)

array([[2],
       [3],
       [1]])

In [30]:
np.diag(arr)

array([3, 6])

In [31]:
arr3=np.array([3,4,5,6,7,8,9])


In [32]:
np.diag(arr3)

array([[3, 0, 0, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 9]])

In [55]:
arr4=np.random.randint(-12,100,[1,50])

In [56]:
arr4

array([[ 73,  49,  10,  85,   2,  86,  51,  55,  73,  95,  42,  85,   6,
         82,  66,  89,  99,  66,  94,  33,  54,  51,  20,  41,  44,  45,
          2,  29,  82,  41,  95,  33,  -4,  18,  36,   9,  89,   5,  74,
         31,  71,  91,  60,  83,  63, -12,   3,  -6,  70,  33]])

In [57]:
np.sort(arr4)

array([[-12,  -6,  -4,   2,   2,   3,   5,   6,   9,  10,  18,  20,  29,
         31,  33,  33,  33,  36,  41,  41,  42,  44,  45,  49,  51,  51,
         54,  55,  60,  63,  66,  66,  70,  71,  73,  73,  74,  82,  82,
         83,  85,  85,  86,  89,  89,  91,  94,  95,  95,  99]])

In [58]:
np.count_nonzero(arr4)

50

In [59]:
np.extract(arr4>22,arr4)

array([73, 49, 85, 86, 51, 55, 73, 95, 42, 85, 82, 66, 89, 99, 66, 94, 33,
       54, 51, 41, 44, 45, 29, 82, 41, 95, 33, 36, 89, 74, 31, 71, 91, 60,
       83, 63, 70, 33])

In [60]:
np.extract(arr4>29,arr4)

array([73, 49, 85, 86, 51, 55, 73, 95, 42, 85, 82, 66, 89, 99, 66, 94, 33,
       54, 51, 41, 44, 45, 82, 41, 95, 33, 36, 89, 74, 31, 71, 91, 60, 83,
       63, 70, 33])

In [61]:
np.where(arr4>10)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([ 0,  1,  3,  5,  6,  7,  8,  9, 10, 11, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 33, 34, 36, 38, 39, 40,
        41, 42, 43, 44, 48, 49]))

In [62]:
d=arr4.view()

In [63]:
d[0][0]=10000

In [64]:
arr4

array([[10000,    49,    10,    85,     2,    86,    51,    55,    73,
           95,    42,    85,     6,    82,    66,    89,    99,    66,
           94,    33,    54,    51,    20,    41,    44,    45,     2,
           29,    82,    41,    95,    33,    -4,    18,    36,     9,
           89,     5,    74,    31,    71,    91,    60,    83,    63,
          -12,     3,    -6,    70,    33]])