In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent=["A glass of milk",
      "A glass of water",
      "I am a good developer",
      "I am a good football player",
      "I am interested in ML and AI",
      "Shyam is good at coding mainly JAVA",
      ]

In [5]:
sent

['A glass of milk',
 'A glass of water',
 'I am a good developer',
 'I am a good football player',
 'I am interested in ML and AI',
 'Shyam is good at coding mainly JAVA']

In [6]:
### Defining Vocabulary Size
voc_size=10000

In [8]:
onehot_repre=[one_hot(words,voc_size) for words in sent]
print(onehot_repre)

[[3602, 3020, 3050, 5503], [3602, 3020, 3050, 8824], [8531, 7867, 3602, 9185, 7393], [8531, 7867, 3602, 9185, 2927, 8523], [8531, 7867, 171, 5579, 4535, 5469, 4338], [9331, 7588, 9185, 6757, 1220, 5594, 9099]]


In [15]:
### Word Embedding Techniques
import numpy as np

In [16]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [17]:
model=Sequential()

In [20]:
embedding_docs=pad_sequences(onehot_repre,padding='pre',maxlen=8)
print(embedding_docs)

[[   0    0    0    0 3602 3020 3050 5503]
 [   0    0    0    0 3602 3020 3050 8824]
 [   0    0    0 8531 7867 3602 9185 7393]
 [   0    0 8531 7867 3602 9185 2927 8523]
 [   0 8531 7867  171 5579 4535 5469 4338]
 [   0 9331 7588 9185 6757 1220 5594 9099]]


In [23]:
model.add(Embedding(voc_size,10,input_length=8))
model.compile('adam','mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [25]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (6, 8, 10)                  │         100,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ embedding_1 (Embedding)              │ (6, 8, 10, 10)              │         100,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ embedding_2 (Embedding)              │ (6, 8, 10, 10, 10)          │         100,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 300,000 (1.14 MB)

 Trainable params: 300,000 (1.14 MB)

 Non-trainable params: 0 (0.00 B)

In [24]:
print(model.predict(embedding_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 766ms/step
[[[[[-0.02441775  0.00711883 -0.00094205 ...  0.031293   -0.01896
     -0.00684841]
    [-0.02441775  0.00711883 -0.00094205 ...  0.031293   -0.01896
     -0.00684841]
    [-0.02441775  0.00711883 -0.00094205 ...  0.031293   -0.01896
     -0.00684841]
    ...
    [-0.02441775  0.00711883 -0.00094205 ...  0.031293   -0.01896
     -0.00684841]
    [-0.02441775  0.00711883 -0.00094205 ...  0.031293   -0.01896
     -0.00684841]
    [-0.02441775  0.00711883 -0.00094205 ...  0.031293   -0.01896
     -0.00684841]]

   [[-0.02441775  0.00711883 -0.00094205 ...  0.031293   -0.01896
     -0.00684841]
    [-0.02441775  0.00711883 -0.00094205 ...  0.031293   -0.01896
     -0.00684841]
    [-0.02441775  0.00711883 -0.00094205 ...  0.031293   -0.01896
     -0.00684841]
    ...
    [-0.02441775  0.00711883 -0.00094205 ...  0.031293   -0.01896
     -0.00684841]
    [-0.02441775  0.00711883 -0.00094205 ...  0.031293   -0.01896
     -0.00684841]
    [-0.02441775  0